#!/bin/bash

if [ "${MLIBDIR}" ];then
  C_LIBDIRS="${B_LIBDIRS}/${MLIBDIR}";
 else
  C_LIBDIRS="${B_LIBDIRS}"
fi;

if [ ! -e ${ARCHROOT}/${1}/usr/${C_LIBDIRS}/locale/locale-archive ];then
  make DESTDIR=${3} localedata/install-locales
 else
  if [ ! -d ${3}/usr/${C_LIBDIRS}/locale ];then
    mkdir ${3}/usr/${C_LIBDIRS}/locale
  fi;
  cp ${ARCHROOT}/${1}/usr/${C_LIBDIRS}/locale/locale-archive ${3}/usr/${C_LIBDIRS}/locale
fi;

case ${1} in
  x86_64)
    if [ -d /build/x86_32 ];then
      /usr/bin/rsync -avP ${3}/lib64 /build/x86_32/
      /usr/bin/rsync -avP ${3}/usr/lib64 /build/x86_32/usr/
    fi;
    if [ "${BOOTSTRAP_STATIC}" == "0" ];then
      /usr/bin/rsync -avP ${3}/lib64 /
      /usr/bin/rsync -avP ${3}/usr/lib64 /usr/
    fi;
  ;;
  x86_32)
    if [ -d /build/x86_64 ];then
      /usr/bin/rsync -avP ${3}/libx32 /build/x86_64/
      /usr/bin/rsync -avP ${3}/usr/libx32 /build/x86_64/usr/
    fi;
    if [ "${BOOTSTRAP_STATIC}" == "0" ];then
      /usr/bin/rsync -avP ${3}/libx32 /
      /usr/bin/rsync -avP ${3}/usr/libx32 /usr/
    fi;
  ;;
  i686)
    if [ -d /build/x86_32 ];then
      /usr/bin/rsync -avP ${3}/lib /build/x86_32/
      /usr/bin/rsync -avP ${3}/usr/lib /build/x86_32/usr/
    fi;
    if [ -d /build/x86_64 ];then
      /usr/bin/rsync -avP ${3}/lib /build/x86_64/
      /usr/bin/rsync -avP ${3}/usr/lib /build/x86_64/usr/
    fi;
    if [ "${BOOTSTRAP_STATIC}" == "0" ];then
      /usr/bin/rsync -avP ${3}/lib /
      /usr/bin/rsync -avP ${3}/usr/lib /usr/
    fi;
  ;;
esac;


#Install no longer installed headers
#We use tirpc / portablexdr now
cd ${2}
if [ ! -d ${3}/usr/include/rpc ];then
  mkdir ${3}/usr/include/rpc
fi;
if [ ! -d ${3}/usr/include/rpcsvc ];then
  mkdir ${3}/usr/include/rpcsvc
fi;
cp sunrpc/rpc/*.h ${3}/usr/include/rpc
cp sunrpc/rpcsvc/*.h nis/rpcsvc/*.h ${3}/usr/include/rpcsvc
rm -f ${3}/usr/include/rpcsvc/rquota.h

#Setup ld.so.conf
mkdir -p ${3}/etc/ld.so.conf.d
echo "include /etc/ld.so.conf.d/*.conf" > ${3}/etc/ld.so.conf

(cat <<EOF
/${B_LIBDIRS}
/usr/${B_LIBDIRS}
EOF
) > ${3}/etc/ld.so.conf.d/glibc_${1}.conf

if [ ! -e ${3}/usr/include/gnu/stubs-x32.h  ] && [ -e ${3}/usr/include/gnu/stubs-64.h ];then
  ln -s stubs-64.h ${3}/usr/include/gnu/stubs-x32.h
fi;

if [ ! -e ${3}/usr/include/gnu/stubs-32.h  ];then
  touch ${3}/usr/include/gnu/stubs-32.h
fi;

if [ -e ${3}/etc/ld.so.cache ];then
  rm ${3}/etc/ld.so.cache
fi;

if [ "${MLIBDIR}" ];then
  mv ${3}/usr/${B_LIBDIRS}/${MLIBDIR}/*.o ${3}/usr/${B_LIBDIRS}/
  (cat <<EOF
/${B_LIBDIRS}/${MLIBDIR}
/usr/${B_LIBDIRS}/${MLIBDIR}
EOF
) > ${3}/etc/ld.so.conf.d/glibc_${1}_mlib.conf
fi;
