typedef enum
{
  GLIBC_MALLOC,
  GLIBC_MALLOC_CHECK,
  GLIBC_MALLOC_TOP_PAD,
  GLIBC_MALLOC_PERTURB,
  GLIBC_MALLOC_MMAP_THRESHOLD,
  GLIBC_MALLOC_TRIM_THRESHOLD,
  GLIBC_MALLOC_MMAP_MAX,
  GLIBC_MALLOC_ARENA_MAX,
  GLIBC_MALLOC_ARENA_TEST,
  TUNABLES_MAX
} tunable_id_t;
